name: Main CI

on: push

jobs:
  Init_and_test:
    name: Init and Test

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.12.1
          cache: npm
      - name: Initialise npm
        run: npm ci
      - name: Perform Static Analysis with ESLint
        run: npx eslint -o eslint_report.json -f json
        continue-on-error: true
      - name: Create ESLint Annotations
        uses: ataylorme/eslint-annotate-action@v3
        with:
          only-pr-files: false
      - name: Run Jest Tests
        run: npm test
      - name: Upload Jest Test Reports
        uses: actions/upload-artifact@v4
        with:
          name: jest-test-results
          path: coverage # Path where Jest stores test reports
